#!/bin/bash
systemctl stop bot.service
rm -rf /home/pi/lbminh-bot/include
rm /home/pi/lbminh-bot/dem.py
cd /lbminh-bot
rm dem.so
wget -r --no-parent  https://github.com/drlbminh/lbminh-bot/blob/master/dem.so
systemctl start bot.service
